### ISSUE TITLE
Can't see when CSS variables are clicked

### ISSUE THREAD

**Issue by madebyernie** [krstivoja/_Swiss-Knife#1]
Can I just say I'm loving this and it makes a huge difference....but there are a few little issues.  This is one.
Whenever I click on any of the CSS variables to edit anything, you can't see what has been clicked.  It does seem to work but the buttons do not go blue or have a border or anything so it's impossible to see what has been selected.

Here is a quick screencast to show what I mean:
http://somup.com/cYe6IAhAAf

**Comment by krstivoja** [comment]
Updated @madebyernie
